### ISSUE TITLE
Compatibilty with android

### ISSUE THREAD

**Issue by Mohit4050** [cemfi/meico#22]
Hi Sir,
Can I use this library for my android project as need to convert PCM to mp3 format. 
thanks & regards
newbie :)

**Comment by axelberndt** [comment]
Hi, I have never tested meico on Android. I think it should work there, too. So, try it out and tell me of your experiences. However, for PCM-to-MP3 encoding you don't really need the whole meico framework. Meico relys on the [Java LAME](https://github.com/nwaldispuehl/java-lame) library for this and you may consider using it directly. In meico's class `meico.audio.Audio` you find method [`encodePcmToMp3()`](https://github.com/cemfi/meico/blob/ec299c8a651abee98c0698833c679f7c6f2be463/src/meico/audio/Audio.java#L223) that shows how to do it. So you may just copy the required code snippets from this class into your code. Anyway, if you find meico more convenient, feel free to use it in your project.
