### ISSUE TITLE
Expand repetitions

### ISSUE THREAD

**Issue by sonovice** [cemfi/meico#3]
It would be nice being able to expand repetitions and prima e seconda volta in MEI files so that the relevant sections are copied several times behind each other.

**Comment by axelberndt** [comment]
Repetition and ending support is in. But I do not rewrite the MEI source. Instead, I generate a sequencingMap in MSM which can be resolved. This causes all MSM maps to be expanded and the deletion of the sequencingMap. From then on, MIDI and audio export will contain all repetitions.
