### ISSUE TITLE
Errors when compiling with ant 

### ISSUE THREAD

**Issue by ajaco56** [cemfi/meico#30]
Hi

When trying to compile the project  on MacOS BIG SUR with ant , I am getting following errors:

 **[javac] /Users/Andreas/meico/src/meico/mei/Mei2MusicXmlConverter.java:3: error: package com.sun.xml.internal.ws.util does not exist
    [javac] import com.sun.xml.internal.ws.util.StringUtils;
    [javac]                                    ^**
    [javac] /Users/Andreas/meico/src/meico/midi/Midi2AudioRenderer.java:3: warning: AudioSynthesizer is internal proprietary API and may be removed in a future release
    [javac] import com.sun.media.sound.AudioSynthesizer;
    [javac]                           ^
    **[javac] /Users/Andreas/meico/src/meico/mei/Mei2MusicXmlConverter.java:1389: error: cannot find symbol
    [javac]         addressBuilder.insert(0, StringUtils.capitalize(e.getLocalName()) +  ":"); // Distributor and Address have very similar children
    [javac]                                  ^**

_ant -version
Apache Ant(TM) version 1.10.15 compiled on August 25 2024

java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)_

Please advice

Regards

Andreas Maria Jacobs

**Comment by axelberndt** [comment]
Hi Andreas, thanks for this notice. I'll have a look into it. Give me some time, please.

**Comment by ajaco56** [comment]
Hi Axel,

another question , althought I can build **meico.jar** succesful when ommiting sun import and not capitalize string in line 1389 of Mei2MusicXmlConverter.java. I do not find a way to build **meicoApp.jar** from source

How to do that?

Regards

Andreas

**Comment by axelberndt** [comment]
The meicoApp is a self-contained project to be found in the meicoApp branch. So, download that branch into a different folder. Once you have your compiled `meico.jar`, it is the external to be used in meicoApp. So just replace the old `meico.jar` in meicoApp's `externals` folder and recompile meicoApp. The main class/entry point for execution is class `meico.app.Main.java`. Take care that your JDK distribution still contains JavaFX! MeicoApp relies on that for its GUI.

**Comment by ajaco56** [comment]
Thanks!
But...

How to compile meicoApp? Maybe you can guide me through it?

A.

**Comment by axelberndt** [comment]
I work with IntelliJ. 

1. There I add the `meico.jar` as a module to the project structure. 
2. In the "Artifacts" section of the project structure add a new artifact, which I called "meicoApp". 
3. In the "Available Elements" of that artifact you find `meico.jar`, right-click and choose "Extract into output root".
4. On the left side of that table, click on `meicoApp.jar`,set the manifest to `yourmeicoappfolder\src\META-INF\MANIFEST.MF` and set the main class to `meico.app.Main`.

This should be it. 

Sidenote: I usually compile with JDK 1.8.0_172. As said, as long as your JDK version ships with JavaFX it should work.

**Comment by ajaco56** [comment]
Ok , I'll try with Eclipse and  let you know 

I am trying to make a MacOS app of it , it works with your prebuild meicoApp.jar , but having issues with the cfg file when it is an app. Apparently it does not look in the correct folder when launched by FInder 

From the terminal it runs fine 

I keep you posted

Thanks so far

Andreas

**Comment by ajaco56** [comment]
Hi Axel,

It works!

meicoAPP.cfg and meicoApp.log are now per default stored in the home directory of the logged in user

If you want I can send you a zipped example MacOS application. Just let me know

Best

Andreas

**Comment by axelberndt** [comment]
Great, thanks! Did you have to set these directories in the code or did that work automatically? Because usually these files are created in the program directory.

And we will nonetheless have a look into the initial error you encountered and find a fix.

**Comment by ajaco56** [comment]
Yes, I changed it in the code 

I am still wondering what _program directory_ actually means. I noticed that apparently it was using the directory from which the jar was initiated .

Also midi playback is not working when using a sf2 font using several banks . So how to  force to just play the first found bank in the font?

With other words, will it be possible to select the bank from the user's soundfont, if that soundfont has several banks (voices). Like it is done with MuseScore 4?

Looking forward to the results of the initial error

Best

Andreas

**Comment by axelberndt** [comment]
Hi Andreas,

I have just uploaded a little fix in class `meico.mei.Mei2MusicXmlConverter` for the issue with the `StringUtils` dependency.  Can you test if it works for you now?

Many thanks, Axel

**Comment by ajaco56** [comment]
Hi Axel,

It is working now w/o the previous error!

Thanks for taking the time to correct it!

Leaves the issue that it is not possible to select a specific bank from a soundfont (sf2 format).

Should I make a feature request for that?

Cheers, Andreas

**Comment by axelberndt** [comment]
That would be a great expansion! What I was thinking about some time ago was to have different playing techniques or articulations in the banks, meaning switching the bank would switch the articulation. Problem is, each soundfont is different. Replacing one soundfont by another could destroy the whole music because it might place completely different data in a bank or even leave it empty. Thus, the class `meico.midi.InstrumentsDictionary` will only create ProgramChanges according to the GM standard and never do a BankSelect.

If you know your specific soundfont you can, of course, always add the BankSelect by yourself. Once you have your `meico.midi.Midi` object, you can invoke `getSequence()` and add the BankSelect yourself. Class `meico.midi.EventMaker`, its constants and its method `createControlChange()` should come in handy for that.


What soundfont do you use? Can you tell me more about your usecase?

**Comment by ajaco56** [comment]
I am using the sf2 from this site: http://sonimusicae.free.fr/orguedesalon-en.html, which I like a lot as is has a lot of registers and is sampled per tone 

I am basically using this for renaissance lute/organ  music practice
And like to have some really good sounding soundfonts for that 
Maybe you can point me a good 8-course renaissance lute soundfont ? ( the one I have is terrible)

I will try to follow your suggestion to use midi object and see how far I come

Thanks again for your answers, really appreciated

Best

Andreas

**Comment by ajaco56** [comment]
Hi Axel,

I found the issue with my soundfonts: apparently meico or javafx is expecting at least bank 0 , preset 0 available in the soundfont
When I changed the presets accordingly it started to work
Still trying to select a preset programmatically, but I have good faith that that will succeed now

**Update: I am able to set a PC programmatically but only thru a conversion from midi to msm to midi. A bit akward indeed**

Cheers

Andreas

**Comment by axelberndt** [comment]
Hi,

well, meico expects per default a  General MIDI (GM, see https://en.wikipedia.org/wiki/General_MIDI) agnostic soundfont. Soundfonts that are dedicated to a certain instrument (e.g. organ) are, for sure, not GM. Thus, your workflow will be

1. do the conversions to MIDI,
2. edit the MIDI sequence, add your own ProgramChange and BankSelect events manually.

Quite uncomfortable.

This brings me to an idea for a future extension. It should be possible to read the names of the sounds in a soundfont. It would be great to generate an instruments dictionary from these and map the instrument names of the music at hand to its (ProgramChange, BankSelect) coordinates. In your specific case, as long as the stop names in your MEI match reasonably well with the names in the soundfont, it should then indeed automatically select the right sounds.

If you have the time resources for this, feel free to try it. Basically, you will start by creating a new class in package `meico.midi`, let's call it `SoundfontInstrumentsDictionary`, that extends class `InstrumentsDictionary`. If do not have the resources for this, I will keep it in mind and look into it when time hase come.

Best, Axel
